export const webStyle = {
  mainWrapper: {
    display: "flex",
    fontFamily: "Roboto-Medium",
    flexDirection: "column",
    alignItems: "center",
    paddingBottom: "30px",
    background: "#fff",
  },
  input: {
    borderRadius: "0.5rem",
    border: "1px solid #DCDCDC",
    padding: "0.5rem 1rem",
    fontFamily: "ClotherRegular",
  },
  upload: {
    textTransform: "none",
    display: "block",
    marginTop: "1rem",
  },
  label: {
    color: "var(--Black, #18181E)",
    fontSize: "1rem",
    fontFamily: "ClotherRegular",
  },
  uploadImg: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "100%",
  },
  fontBlock: {
    fontSize: "0.875rem",
    color: "#A1A1A1",
    fontFamily: "ClotherRegular",
  },
  img: {
    width: "20rem",
    objectFit: "contain",
  },
  galleryHeader: {
    margin: "auto",
    width: "fit-content",
    fontSize: "1.5rem",
  },
  editModal: {
    position: "absolute" as "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    boxShadow: "24",
    background: "#fff",
    padding: "1rem",
    borderRadius: "0.5rem",
    maxWidth: "90vw",
  },
  localButton: {
    color: "#fff",
    background: "#8735E1",
    borderRadius: "0.5rem",
    fontSize: "1.25rem",
    cursor: "pointer",
    height: "3.5rem",
    width: "100%",
    border: "none",
  },
  imgButton: {
    cursor: "pointer",
    border: "none",
    background: "transparent",
    width: "1.5rem",
    minWidth: "auto",
    objectFit: "contain",
    color: "#8735e1",
  },
  chip: {
    cursor: "pointer",
    marginRight: "0.5rem",
    lineHeight: "1.6rem",
    height: "100%",
  },
};
